name: Python Package using Conda

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      description:
        description: 'Check'
        required: true
        default: 'False'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10, 3.11]
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          auto-activate-base: false

      - name: Create Conda environment
        run: |
          conda create --name myenv python=${{ matrix.python-version }} --yes
          conda activate myenv

      - name: Install dependencies from requirements.txt
        run: |
          conda activate myenv
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          conda activate myenv
          conda install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          conda activate myenv
          conda install pytest
          pytest
